name: CI

on:
  push:
    branches: [master]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: stable
        flixel-versions: dev
        target: flash
    - run: npm install
      working-directory: api/dox
    - run: haxe --cwd api --run Make xml pages
    - uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: api/dox/out
